import { Question } from '../../model/question';

export const articlesQuestions: Question[] = [
  {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    section: 'articles',
    context: 'Говорим об уникальной Системе, которая управляет миром героя.',
    text: "He heard the robotic voice of <input type='text' id='answer-input'> (a/an/the) System in his head.",
    correct: ['the'],
    rule: "Используем 'The', когда говорим об уникальном объекте или сущности, единственной в своем роде в данном контексте (Система).",
    examples: [
      '<b>The</b> sun is shining.',
      'Connect to <b>the</b> Internet.',
      '<b>The</b> King arrived.',
    ],
  },
  {
    id: 'c9e1b2f3-1234-4567-890a-bcdef1234567',
    section: 'articles',
    context: 'Первое упоминание меча (какой-то меч).',
    text: "The villain picked up <input type='text' id='answer-input'> (a/an/the) sharp sword from the ground.",
    correct: ['a'],
    rule: "Используем неопределенный артикль 'A', когда упоминаем предмет впервые или имеем в виду 'один из', 'какой-то'.",
    examples: [
      'I saw <b>a</b> cat.',
      'He needs <b>a</b> pen.',
      'There is <b>a</b> book on the table.',
    ],
  },
  {
    id: 'd8f2c3a4-5678-9012-3456-7890abcdef12',
    section: 'articles',
    context: 'Говорим о титуле/должности (Глава Секты).',
    text: "He didn't want to be <input type='text' id='answer-input'> (a/an/the) Sect Leader anymore.",
    correct: ['the'],
    rule: "Определенный артикль 'The' используется с титулами и уникальными должностями, когда ясно, о какой именно должности идет речь.",
    examples: [
      '<b>The</b> President of the US.',
      '<b>The</b> captain of the ship.',
      'Who is <b>the</b> boss here?',
    ],
  },
  {
    id: 'e7a1b2c3-4567-8901-2345-67890abcdef1',
    section: 'articles',
    context: 'Абстрактное понятие (ненависть) в общем смысле.',
    text: "The disciple's eyes were full of <input type='text' id='answer-input'> (a/an/the/-) hatred.",
    correct: ['-', ''],
    rule: 'Абстрактные неисчисляемые существительные (love, hate, beauty) в общем смысле используются без артикля (Zero Article).',
    examples: [
      '<b>Love</b> is blind.',
      'He is full of <b>anger</b>.',
      '<b>Time</b> flies.',
    ],
  },
  {
    id: 'f1a2b3c4-d5e6-7890-1234-567890abcdef',
    section: 'articles',
    context: 'Превосходная степень (самый сильный).',
    text: "Alto is <input type='text' id='answer-input'> (a/an/the) strongest mage in the academy.",
    correct: ['the'],
    rule: "Превосходная степень прилагательных (superlatives) всегда требует определенного артикля 'The'.",
    examples: [
      'It is <b>the</b> best day.',
      'She is <b>the</b> smartest girl.',
      'That was <b>the</b> worst mistake.',
    ],
  },
  {
    id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
    section: 'articles',
    context: 'Указание направления (на север).',
    text: "They traveled to <input type='text' id='answer-input'> (a/an/the) North to find the icy cavern.",
    correct: ['the'],
    rule: "Названия сторон света (the North, the South, the East, the West) употребляются с артиклем 'The', когда обозначают регион или направление.",
    examples: [
      'The wind blows from <b>the</b> West.',
      'He lives in <b>the</b> South.',
      'Look to <b>the</b> East.',
    ],
  },
  {
    id: 'b2c3d4e5-f6a7-8901-2345-67890abcdef1',
    section: 'articles',
    context: 'Существительное во множественном числе в общем смысле (демоны).',
    text: "<input type='text' id='answer-input'> (A/The/-) Demons are dangerous creatures.",
    correct: ['-', ''],
    rule: 'Существительные во множественном числе, обозначающие класс объектов в целом, употребляются без артикля.',
    examples: [
      '<b>Cats</b> hate water.',
      '<b>Apples</b> are healthy.',
      '<b>Students</b> should study hard.',
    ],
  },
  {
    id: 'c3d4e5f6-a7b8-9012-3456-7890abcdef12',
    section: 'articles',
    context: 'Упоминание времени суток (утром).',
    text: "The training usually starts in <input type='text' id='answer-input'> (a/an/the) morning.",
    correct: ['the'],
    rule: "С частями суток (morning, afternoon, evening) используется предлог 'in' и артикль 'the'.",
    examples: [
      'I work in <b>the</b> morning.',
      'See you in <b>the</b> evening.',
      'It happened in <b>the</b> afternoon.',
    ],
  },
  {
    id: 'd4e5f6a7-b8c9-0123-4567-890abcdef123',
    section: 'articles',
    context: 'Конструкция "один из" (такой-то ученик).',
    text: "He is <input type='text' id='answer-input'> (a/an/the) very talented disciple.",
    correct: ['a'],
    rule: 'Если перед существительным стоит прилагательное, артикль (a/an) ставится перед прилагательным и зависит от его первого звука.',
    examples: [
      'He is <b>a</b> good man.',
      'It is <b>an</b> interesting book.',
      'She is <b>a</b> nice person.',
    ],
  },
  {
    id: 'e5f6a7b8-c9d0-1234-5678-90abcdef1234',
    section: 'articles',
    context: 'Второй раз упоминаем конкретную книгу.',
    text: "Sheena remembered the plot. <input type='text' id='answer-input'> (A/An/The) book was terrible but addictive.",
    correct: ['The'],
    rule: "При повторном упоминании объекта используется определенный артикль 'The', так как собеседники уже знают, о чем речь.",
    examples: [
      'I bought a car. <b>The</b> car is red.',
      'She has a dog. <b>The</b> dog is big.',
      'We saw a film. <b>The</b> film was boring.',
    ],
  },
  {
    id: 'f6a7b8c9-d0e1-2345-6789-0abcdef12345',
    section: 'articles',
    context: 'Название инструмента (играть на флейте).',
    text: "He learned to play <input type='text' id='answer-input'> (a/an/the) flute to calm his mind.",
    correct: ['the'],
    rule: "С названиями музыкальных инструментов в конструкции 'play + instrument' используется артикль 'the'.",
    examples: [
      'He plays <b>the</b> piano.',
      'Can you play <b>the</b> guitar?',
      'She practices <b>the</b> violin.',
    ],
  },
  {
    id: 'a7b8c9d0-e1f2-3456-7890-abcdef123456',
    section: 'articles',
    context: 'Исчисляемое существительное (час).',
    text: "You have <input type='text' id='answer-input'> (a/an/the) hour to complete the mission.",
    correct: ['an'],
    rule: "Артикль 'An' используется перед словами, начинающимися с гласного *звука*. В слове 'hour' буква 'h' не произносится.",
    examples: [
      'Wait <b>an</b> hour.',
      'He is <b>an</b> honest man.',
      'It is <b>an</b> honor.',
    ],
  },
  {
    id: 'b8c9d0e1-f2a3-4567-8901-bcdef1234567',
    section: 'articles',
    context: 'Название уникального места (Бездна).',
    text: "The villain was thrown into <input type='text' id='answer-input'> (a/an/the) Abyss.",
    correct: ['the'],
    rule: "Названия уникальных географических или мифических мест часто употребляются с 'The' (особенно если есть контекст уникальности).",
    examples: [
      '<b>The</b> Sahara Desert.',
      '<b>The</b> Atlantic Ocean.',
      '<b>The</b> Sky.',
    ],
  },
  {
    id: 'c9d0e1f2-a3b4-5678-9012-cdef12345678',
    section: 'articles',
    context: 'Послеобеденное время (обед).',
    text: "They discussed the plan during <input type='text' id='answer-input'> (a/an/the/-) lunch.",
    correct: ['-', ''],
    rule: 'Названия приемов пищи (breakfast, lunch, dinner) обычно употребляются без артикля.',
    examples: [
      'I had <b>breakfast</b> at 8.',
      'What is for <b>dinner</b>?',
      "Let's meet after <b>lunch</b>.",
    ],
  },
  {
    id: 'd0e1f2a3-b4c5-6789-0123-def123456789',
    section: 'articles',
    context: 'Существительное с уточнением (Мир демонов).',
    text: "He explored <input type='text' id='answer-input'> (a/an/the) World of Demons.",
    correct: ['the'],
    rule: "Конструкция 'N + of + N' (существительное + of + существительное) обычно требует артикль 'The' перед первым словом.",
    examples: [
      '<b>The</b> Queen of England.',
      '<b>The</b> top of the mountain.',
      '<b>The</b> end of the story.',
    ],
  },
  {
    id: 'e1f2a3b4-c5d6-7890-1234-ef1234567890',
    section: 'articles',
    context: 'Прилагательное в роли группы людей (Богатые/Бедные).',
    text: "In this cultivation world, <input type='text' id='answer-input'> (a/an/the) strong survive.",
    correct: ['the'],
    rule: "Прилагательные с артиклем 'The' могут обозначать группу людей с этим признаком (The rich, The poor, The strong).",
    examples: [
      '<b>The rich</b> should help <b>the poor</b>.',
      '<b>The young</b> have future.',
      'He helps <b>the elderly</b>.',
    ],
  },
  {
    id: 'f2a3b4c5-d6e7-8901-2345-f12345678901',
    section: 'articles',
    context: 'Оборот there is/are с единственным числом.',
    text: "There is <input type='text' id='answer-input'> (a/an/the) traitor among us.",
    correct: ['a'],
    rule: "После оборота 'There is' с исчисляемыми существительными в единственном числе обычно используется артикль 'A/An'.",
    examples: [
      'There is <b>a</b> book.',
      'There is <b>a</b> spider.',
      'There is <b>an</b> apple.',
    ],
  },
  {
    id: 'a3b4c5d6-e7f8-9012-3456-012345678901',
    section: 'articles',
    context: 'Имя собственное (Шина).',
    text: "He realized he was now <input type='text' id='answer-input'> (a/an/the/-) Sheena.",
    correct: ['-', ''],
    rule: 'Имена людей обычно используются без артиклей.',
    examples: [
      'This is <b>John</b>.',
      'I know <b>Mary</b>.',
      '<b>London</b> is a city.',
    ],
  },
  {
    id: 'b4c5d6e7-f8a9-0123-4567-123456789012',
    section: 'articles',
    context: 'Конкретная ситуация (Ситуация вышла из-под контроля).',
    text: "<input type='text' id='answer-input'> (A/An/The) situation was getting out of control.",
    correct: ['The'],
    rule: "Когда говорящий и слушающий понимают, о какой конкретной ситуации идет речь, используется 'The'.",
    examples: [
      '<b>The</b> problem is difficult.',
      '<b>The</b> weather is bad.',
      '<b>The</b> door is open.',
    ],
  },
  {
    id: 'c5d6e7f8-a9b0-1234-5678-234567890123',
    section: 'articles',
    context: 'Порядковое числительное (Первый раз).',
    text: "It was <input type='text' id='answer-input'> (a/an/the) first time he used magic.",
    correct: ['the'],
    rule: "Перед порядковыми числительными (first, second, third) ставится артикль 'The'.",
    examples: [
      'He is <b>the first</b> guest.',
      'Take <b>the second</b> turn.',
      'This is <b>the third</b> time.',
    ],
  },
];
