import { Question } from '../../model/question';

export const prepositionsQuestions: Question[] = [
  {
    id: '7b22d1a0-5c67-4e9f-8a12-1b3c4d5e6f78',
    section: 'prepositions',
    context: 'Бояться чего-то (гнев учителя).',
    text: "The young disciple was afraid <input type='text' id='answer-input'> (of/from/by) his Master's anger.",
    correct: ['of'],
    rule: 'Устойчивое выражение: to be afraid OF something (бояться чего-то).',
    examples: [
      'I am afraid <b>of</b> spiders.',
      'Are you afraid <b>of</b> the dark?',
      "Don't be afraid <b>of</b> me.",
    ],
  },
  {
    id: '8c33e2b1-6d78-5f0a-9b23-2c4d5e6f7a89',
    section: 'prepositions',
    context: 'Слушать кого-то (Систему).',
    text: "He had no choice but to listen <input type='text' id='answer-input'> (at/to/on) the annoying voice.",
    correct: ['to'],
    rule: 'Глагол listen всегда требует предлога TO перед объектом (listen TO someone/something).',
    examples: [
      'Listen <b>to</b> me!',
      'He listens <b>to</b> music.',
      'She never listens <b>to</b> advice.',
    ],
  },
  {
    id: '9d44f3c2-7e89-6a1b-0c34-3d5e6f7a8b90',
    section: 'prepositions',
    context: 'Ждать кого-то (ждать героя).',
    text: "Sheena was waiting <input type='text' id='answer-input'> (to/for/at) Alto to return.",
    correct: ['for'],
    rule: 'Глагол wait используется с предлогом FOR перед объектом ожидания (wait FOR someone).',
    examples: [
      'Wait <b>for</b> me.',
      'He is waiting <b>for</b> the bus.',
      'We waited <b>for</b> an hour.',
    ],
  },
  {
    id: '0e55a4d3-8f90-7b2c-1d45-4e6f7a8b9c01',
    section: 'prepositions',
    context: 'Прибыть в место (в город).',
    text: "When they arrived <input type='text' id='answer-input'> (at/to/in) the city, it was raining.",
    correct: ['in'],
    rule: 'Arrive IN используется с городами и странами. Arrive AT — с конкретными местами (здания, станции). Arrive TO — неверно.',
    examples: [
      'We arrived <b>in</b> London.',
      'They arrived <b>in</b> France.',
      'He arrived <b>at</b> the airport.',
    ],
  },
  {
    id: '1f66b5e4-9a01-8c3d-2e56-5f7a8b9c0d12',
    section: 'prepositions',
    context: 'Злиться на кого-то.',
    text: "The System was angry <input type='text' id='answer-input'> (on/with/at) the host for breaking character.",
    correct: ['with', 'at'],
    rule: 'To be angry WITH (или AT) someone — злиться на кого-то.',
    examples: [
      'She is angry <b>with</b> me.',
      "Don't be angry <b>with</b> him.",
      'Why are you angry <b>at</b> the world?',
    ],
  },
  {
    id: '2a77c6f5-0b12-9d4e-3f67-6a8b9c0d1e23',
    section: 'prepositions',
    context: 'Зависеть от чего-то (от очков B-points).',
    text: "His survival depends <input type='text' id='answer-input'> (from/of/on) his B-points.",
    correct: ['on'],
    rule: 'Глагол depend всегда используется с предлогом ON (depend ON).',
    examples: [
      'It depends <b>on</b> you.',
      'Success depends <b>on</b> hard work.',
      'Do not depend <b>on</b> luck.',
    ],
  },
  {
    id: '3b88d7a6-1c23-0e5f-4a78-7b9c0d1e2f34',
    section: 'prepositions',
    context: 'Смотреть на что-то (на экран).',
    text: "He looked <input type='text' id='answer-input'> (on/at/to) the blue holographic screen in shock.",
    correct: ['at'],
    rule: 'Look AT — смотреть на что-то. Look FOR — искать. Look AFTER — присматривать.',
    examples: [
      'Look <b>at</b> the sky.',
      'He looked <b>at</b> her.',
      'Stop looking <b>at</b> me.',
    ],
  },
  {
    id: '4c99e8b7-2d34-1f6a-5b89-8c0d1e2f3a45',
    section: 'prepositions',
    context: 'Интересоваться чем-то (магией).',
    text: "He was never interested <input type='text' id='answer-input'> (at/in/about) dark magic before.",
    correct: ['in'],
    rule: 'Выражение interested IN — интересоваться чем-то.',
    examples: [
      'I am interested <b>in</b> art.',
      'Are you interested <b>in</b> this book?',
      'She is interested <b>in</b> learning.',
    ],
  },
  {
    id: '5d00f9c8-3e45-2a7b-6c90-9d1e2f3a4b56',
    section: 'prepositions',
    context: 'Избавиться от чего-то.',
    text: "He wanted to get rid <input type='text' id='answer-input'> (from/of/off) the annoying System.",
    correct: ['of'],
    rule: 'Устойчивое выражение: get rid OF something (избавиться от).',
    examples: [
      'Get rid <b>of</b> this trash.',
      'I want to get rid <b>of</b> my car.',
      'He got rid <b>of</b> the problem.',
    ],
  },
  {
    id: '6e11a0d9-4f56-3b8c-7d01-0e2f3a4b5c67',
    section: 'prepositions',
    context: 'Входить в комнату (без предлога).',
    text: "Alto entered <input type='text' id='answer-input'> (in/into/-) the room silently.",
    correct: ['-', ''],
    rule: "Глагол enter (в значении 'войти в помещение') используется БЕЗ предлога.",
    examples: [
      'He <b>entered</b> the house.',
      'She <b>entered</b> the hall.',
      'They <b>entered</b> the cave.',
    ],
  },
  {
    id: '7f22b1e0-5a67-4c9d-8e12-1f3a4b5c6d78',
    section: 'prepositions',
    context: 'Быть добрым к кому-то.',
    text: "Why are you so kind <input type='text' id='answer-input'> (for/to/with) your enemy?",
    correct: ['to'],
    rule: 'Kind TO, Polite TO, Rude TO — описывает отношение к кому-то.',
    examples: [
      'Be kind <b>to</b> animals.',
      'She is very kind <b>to</b> me.',
      'He was not kind <b>to</b> her.',
    ],
  },
  {
    id: '8a33c2f1-6b78-5d0e-9f23-2a4b5c6d7e89',
    section: 'prepositions',
    context: 'Обвинять в чем-то.',
    text: "They accused him <input type='text' id='answer-input'> (in/of/for) treason.",
    correct: ['of'],
    rule: 'Accuse OF doing something / Accuse OF a crime — обвинять в чем-то.',
    examples: [
      'He is accused <b>of</b> theft.',
      'They accused her <b>of</b> lying.',
      'I accuse you <b>of</b> nothing.',
    ],
  },
  {
    id: '9b44d3a2-7c89-6e1f-0a34-3b5c6d7e8f90',
    section: 'prepositions',
    context: 'Думать о чем-то (размышлять).',
    text: "He thought <input type='text' id='answer-input'> (about/on/for) the plot of the novel.",
    correct: ['about'],
    rule: 'Think ABOUT — обдумывать, размышлять о предмете.',
    examples: [
      'I think <b>about</b> you.',
      'Think <b>about</b> the future.',
      'What are you thinking <b>about</b>?',
    ],
  },
  {
    id: '0c55e4b3-8d90-7f2a-1b45-4c6d7e8f9a01',
    section: 'prepositions',
    context: 'Отвечать за что-то (быть ответственным).',
    text: "Who is responsible <input type='text' id='answer-input'> (at/for/of) this mess?",
    correct: ['for'],
    rule: 'Responsible FOR — ответственный за.',
    examples: [
      'I am responsible <b>for</b> the team.',
      'Who is responsible <b>for</b> this?',
      'She is responsible <b>for</b> cleaning.',
    ],
  },
  {
    id: '1d66f5c4-9e01-8a3b-2c56-5d7e8f9a0b12',
    section: 'prepositions',
    context: 'Умереть от чего-то (от яда).',
    text: "The villain didn't want to die <input type='text' id='answer-input'> (from/of/by) poison again.",
    correct: ['of', 'from'],
    rule: 'Die OF (или FROM) a disease/cause. Die OF hunger/cancer/poison.',
    examples: [
      'He died <b>of</b> hunger.',
      'She died <b>of</b> old age.',
      'Many died <b>of</b> the plague.',
    ],
  },
  {
    id: '2e77a6d5-0f12-9b4c-3d67-6e8f9a0b1c23',
    section: 'prepositions',
    context: 'Извиняться перед кем-то.',
    text: "He apologized <input type='text' id='answer-input'> (to/before/at) his disciple.",
    correct: ['to'],
    rule: 'Apologize TO someone (перед кем-то) FOR something (за что-то).',
    examples: [
      'Apologize <b>to</b> your sister.',
      'He apologized <b>to</b> me.',
      'I must apologize <b>to</b> him.',
    ],
  },
  {
    id: '3f88b7e6-1a23-0c5d-4e78-7f9a0b1c2d34',
    section: 'prepositions',
    context: 'Относиться к чему-то (принадлежать).',
    text: "This sword belongs <input type='text' id='answer-input'> (at/to/for) the Sect Leader.",
    correct: ['to'],
    rule: 'Belong TO — принадлежать кому-то.',
    examples: [
      'This bag belongs <b>to</b> me.',
      'It belongs <b>to</b> the museum.',
      'Does this belong <b>to</b> you?',
    ],
  },
  {
    id: '4a99c8f7-2b34-1d6e-5f89-8a0b1c2d3e45',
    section: 'prepositions',
    context: 'Похожий на (сходство).',
    text: "This world is very similar <input type='text' id='answer-input'> (with/to/at) the one in the book.",
    correct: ['to'],
    rule: 'Similar TO — похожий на.',
    examples: [
      'Your car is similar <b>to</b> mine.',
      'It is similar <b>to</b> a cat.',
      'They are similar <b>to</b> each other.',
    ],
  },
  {
    id: '5b00d9a8-3c45-2e7f-6a90-9b1c2d3e4f56',
    section: 'prepositions',
    context: 'Гордиться кем-то.',
    text: "Deep down, he was proud <input type='text' id='answer-input'> (for/of/about) his student's progress.",
    correct: ['of'],
    rule: 'Proud OF — гордиться кем-то/чем-то.',
    examples: [
      'I am proud <b>of</b> you.',
      'He is proud <b>of</b> his son.',
      'Be proud <b>of</b> your work.',
    ],
  },
  {
    id: '6c11e0b9-4d56-3f8a-7b01-0c2d3e4f5a67',
    section: 'prepositions',
    context: 'Хорош в чем-то (навык).',
    text: "Sheena was good <input type='text' id='answer-input'> (in/at/on) acting like a villain.",
    correct: ['at'],
    rule: 'Good AT doing something — хорош в каком-то деле.',
    examples: [
      'He is good <b>at</b> math.',
      'She is good <b>at</b> swimming.',
      'Are you good <b>at</b> chess?',
    ],
  },
];
