import { Question } from '../../model/question';

export const verbsQuestions: Question[] = [
  {
    id: '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
    section: 'verbs',
    context: 'Длительное действие в прошлом (читал), прерванное другим.',
    text: "Shen was <input type='text' id='answer-input'> (read) the novel when he choked on a bun.",
    correct: ['reading'],
    rule: 'Past Continuous (was/were + V-ing) используется для описания действия, которое длилось в определенный момент в прошлом.',
    examples: [
      'I <b>was sleeping</b> when you called.',
      'She <b>was working</b> all day.',
      'They <b>were eating</b> dinner.',
    ],
  },
  {
    id: '2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e',
    section: 'verbs',
    context: 'Предшествующее действие (умер до того, как попал в книгу).',
    text: "He realized that he <input type='text' id='answer-input'> (die) in his previous life.",
    correct: ['had died'],
    rule: 'Past Perfect (had + V3) используется для действия, которое произошло *до* другого действия в прошлом.',
    examples: [
      'She <b>had left</b> before I arrived.',
      'He <b>had finished</b> the work by 5 PM.',
      'They <b>had gone</b> home.',
    ],
  },
  {
    id: '3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f',
    section: 'verbs',
    context: 'Условное предложение 1 типа (реальное будущее).',
    text: "If you <input type='text' id='answer-input'> (break) character, the System will punish you.",
    correct: ['break'],
    rule: 'First Conditional: If + Present Simple, ... Future Simple. В части с IF будущее время не ставится.',
    examples: [
      'If it <b>rains</b>, I will stay home.',
      'If he <b>comes</b>, tell me.',
      'If you <b>study</b>, you will pass.',
    ],
  },
  {
    id: '4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a',
    section: 'verbs',
    context: 'Модальный глагол обязательства (должен).',
    text: "You <input type='text' id='answer-input'> (must/can/may) complete the mission to survive.",
    correct: ['must', 'have to'],
    rule: 'Must выражает сильную необходимость или обязанность.',
    examples: [
      'You <b>must</b> go now.',
      'I <b>must</b> finish this.',
      'We <b>must</b> obey the rules.',
    ],
  },
  {
    id: '5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b',
    section: 'verbs',
    context: 'Конструкция used to (раньше делал, сейчас нет).',
    text: "The original villain <input type='text' id='answer-input'> (use) to beat his disciples.",
    correct: ['used'],
    rule: 'Used to + инфинитив описывает привычки или состояния в прошлом, которых больше нет.',
    examples: [
      'I <b>used to</b> smoke.',
      'He <b>used to</b> live here.',
      'She <b>used to</b> be shy.',
    ],
  },
  {
    id: '6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c',
    section: 'verbs',
    context: 'Сложное дополнение (заставить кого-то сделать).',
    text: "The System made him <input type='text' id='answer-input'> (do) stupid things.",
    correct: ['do'],
    rule: "После глагола 'make' (в значении заставлять) используется инфинитив БЕЗ частицы 'to'.",
    examples: [
      "Don't make me <b>cry</b>.",
      'He made her <b>laugh</b>.',
      'They made us <b>wait</b>.',
    ],
  },
  {
    id: '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
    section: 'verbs',
    context: 'Пассивный залог (был отправлен).',
    text: "The protagonist <input type='text' id='answer-input'> (send) to the Abyss by his master.",
    correct: ['was sent'],
    rule: 'Past Simple Passive: was/were + V3 (причастие прошедшего времени).',
    examples: [
      'The letter <b>was written</b> yesterday.',
      'The car <b>was stolen</b>.',
      'They <b>were invited</b> to the party.',
    ],
  },
  {
    id: '8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e',
    section: 'verbs',
    context: 'Инфинитив цели (остановился, чтобы посмотреть).',
    text: "He stopped <input type='text' id='answer-input'> (look) at the strange flower.",
    correct: ['to look'],
    rule: 'Stop + to V — остановиться, чтобы сделать что-то. Stop + V-ing — прекратить делать что-то.',
    examples: [
      'He stopped <b>to smoke</b> (остановился покурить).',
      'He stopped <b>smoking</b> (бросил курить).',
      'I stopped <b>to rest</b>.',
    ],
  },
  {
    id: '9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f',
    section: 'verbs',
    context: 'Отрицание в прошлом (не знал).',
    text: "He <input type='text' id='answer-input'> (not know) how to use a sword.",
    correct: ['did not know', "didn't know"],
    rule: "В Past Simple отрицание строится с помощью вспомогательного глагола DID NOT (didn't) + начальная форма глагола.",
    examples: [
      "I <b>didn't go</b> there.",
      "She <b>didn't see</b> him.",
      "We <b>didn't want</b> this.",
    ],
  },
  {
    id: '0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a',
    section: 'verbs',
    context: 'Present Perfect (только что случилось).',
    text: "I <input type='text' id='answer-input'> (just/finish) reading the last chapter.",
    correct: ['have just finished'],
    rule: "Present Perfect (have/has + V3) используется с наречием 'just' для действий, завершившихся только что.",
    examples: [
      'I <b>have just arrived</b>.',
      'She <b>has just left</b>.',
      'We <b>have just eaten</b>.',
    ],
  },
  {
    id: '1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b',
    section: 'verbs',
    context: 'Герундий после предлога (о побеге).',
    text: "He thought about <input type='text' id='answer-input'> (escape) from the sect.",
    correct: ['escaping'],
    rule: 'После предлогов глагол всегда ставится в форму герундия (V-ing).',
    examples: [
      'She is good at <b>painting</b>.',
      'Thank you for <b>coming</b>.',
      'He left without <b>saying</b> goodbye.',
    ],
  },
  {
    id: '2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c',
    section: 'verbs',
    context: 'Косвенная речь (сказал, что он...).',
    text: "Alto said that he <input type='text' id='answer-input'> (be) ready to fight.",
    correct: ['was'],
    rule: 'Согласование времен: если главное предложение в прошлом (said), то придаточное тоже сдвигается в прошлое (is -> was).',
    examples: [
      'He said he <b>was</b> busy.',
      'She told me she <b>liked</b> it.',
      'They said they <b>were</b> coming.',
    ],
  },
  {
    id: '3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d',
    section: 'verbs',
    context: 'Вопрос в Present Simple (Что это значит?).',
    text: "What <input type='text' id='answer-input'> (do) this error message mean?",
    correct: ['does'],
    rule: 'В вопросах Present Simple с 3-м лицом ед.ч. (message = it) используется вспомогательный глагол DOES.',
    examples: [
      'What <b>does</b> he want?',
      'Where <b>does</b> she live?',
      'How <b>does</b> it work?',
    ],
  },
  {
    id: '4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e',
    section: 'verbs',
    context: 'Условное предложение 2 типа (нереальное: если бы я был...).',
    text: "If I <input type='text' id='answer-input'> (be) you, I would run away.",
    correct: ['were'],
    rule: "Second Conditional: If + Past Simple, ... would + V. Глагол 'be' в условии часто принимает форму 'were' для всех лиц.",
    examples: [
      'If I <b>were</b> rich, I would buy a castle.',
      'If he <b>were</b> here, he would help.',
      'If she <b>were</b> younger, she would travel.',
    ],
  },
  {
    id: '5c6d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f',
    section: 'verbs',
    context: 'Отказ что-то делать (refuse + to).',
    text: "The Master refused <input type='text' id='answer-input'> (answer) the question.",
    correct: ['to answer'],
    rule: "После глагола 'refuse' используется инфинитив с частицей 'to'.",
    examples: [
      'He refused <b>to go</b>.',
      'She refused <b>to help</b>.',
      'They refused <b>to pay</b>.',
    ],
  },
  {
    id: '6d7e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a',
    section: 'verbs',
    context: 'Избегать действия (avoid + ing).',
    text: "He tried to avoid <input type='text' id='answer-input'> (meet) the protagonist.",
    correct: ['meeting'],
    rule: "После глагола 'avoid' используется герундий (V-ing).",
    examples: [
      'Avoid <b>talking</b> to strangers.',
      'He avoids <b>working</b> late.',
      'She avoids <b>eating</b> sugar.',
    ],
  },
  {
    id: '7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b',
    section: 'verbs',
    context: 'Будущее время (предсказание/обещание).',
    text: "I promise I <input type='text' id='answer-input'> (protect) you.",
    correct: ['will protect'],
    rule: 'Future Simple (will + V) используется для обещаний и спонтанных решений.',
    examples: [
      'I <b>will help</b> you.',
      'I <b>will call</b> you later.',
      'We <b>will always love</b> you.',
    ],
  },
  {
    id: '8f9a0b1c-2d3e-4f5a-6b7c-8d9e0f1a2b3c',
    section: 'verbs',
    context: 'Would rather (я бы лучше...).',
    text: "I would rather <input type='text' id='answer-input'> (stay) here than go to the dungeon.",
    correct: ['stay'],
    rule: "После конструкции 'would rather' следует 'голый' инфинитив (без to).",
    examples: [
      'I would rather <b>go</b> home.',
      'She would rather <b>not eat</b>.',
      'We would rather <b>wait</b>.',
    ],
  },
  {
    id: '9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d',
    section: 'verbs',
    context: 'Причастие (Летящий меч).',
    text: "He saw a <input type='text' id='answer-input'> (fly) sword in the sky.",
    correct: ['flying'],
    rule: 'Participle I (V-ing) используется в качестве определения (какой? делающий что? - летящий).',
    examples: [
      'A <b>sleeping</b> baby.',
      'A <b>running</b> man.',
      'An <b>interesting</b> book.',
    ],
  },
  {
    id: '0b1c2d3e-4f5a-6b7c-8d9e-0f1a2b3c4d5e',
    section: 'verbs',
    context: 'Позволение (Let him go).',
    text: "Please, let me <input type='text' id='answer-input'> (explain) everything!",
    correct: ['explain'],
    rule: "После глагола 'let' используется инфинитив без частицы 'to'.",
    examples: [
      'Let him <b>speak</b>.',
      'Let me <b>go</b>.',
      'Let us <b>pray</b>.',
    ],
  },
];
