import { Question } from '../../model/question';

export const wordFormationQuestions: Question[] = [
  {
    id: '11a22b33-c44d-55e6-66f7-77a88b99c00d',
    section: 'wordFormation',
    context: 'Существительное от CULTIVATE (процесс).',
    text: "His <input type='text' id='answer-input'> (CULTIVATE) was stuck at the bottleneck.",
    correct: ['cultivation'],
    rule: 'Суффикс -ION образует существительные от глаголов (Cultivate -> Cultivation).',
    examples: [
      'Inform -> <b>Information</b>',
      'Act -> <b>Action</b>',
      'Educate -> <b>Education</b>',
    ],
  },
  {
    id: '22b33c44-d55e-66f7-77a8-88b99c00d11e',
    section: 'wordFormation',
    context: 'Существительное от DARK (темнота).',
    text: "The endless <input type='text' id='answer-input'> (DARK) of the Abyss scared him.",
    correct: ['darkness'],
    rule: 'Суффикс -NESS образует существительные от прилагательных (Dark -> Darkness).',
    examples: [
      'Sad -> <b>Sadness</b>',
      'Kind -> <b>Kindness</b>',
      'Happy -> <b>Happiness</b>',
    ],
  },
  {
    id: '33c44d55-e66f-77a8-88b9-99c00d11e22f',
    section: 'wordFormation',
    context: 'Прилагательное от DANGER (опасный).',
    text: "The demonic beasts are very <input type='text' id='answer-input'> (DANGER).",
    correct: ['dangerous'],
    rule: 'Суффикс -OUS образует прилагательные (Danger -> Dangerous).',
    examples: [
      'Fame -> <b>Famous</b>',
      'Nerve -> <b>Nervous</b>',
      'Poison -> <b>Poisonous</b>',
    ],
  },
  {
    id: '44d55e66-f77a-88b9-99c0-00d11e22f33a',
    section: 'wordFormation',
    context: 'Наречие от SILENT (молча/тихо).',
    text: "Alto <input type='text' id='answer-input'> (SILENT) followed his master.",
    correct: ['silently'],
    rule: 'Суффикс -LY образует наречия от прилагательных (Silent -> Silently).',
    examples: [
      'Quick -> <b>Quickly</b>',
      'Loud -> <b>Loudly</b>',
      'Bad -> <b>Badly</b>',
    ],
  },
  {
    id: '55e66f77-a88b-99c0-00d1-11e22f33a44b',
    section: 'wordFormation',
    context: 'Отрицательное прилагательное от POSSIBLE (невозможно).',
    text: "It is <input type='text' id='answer-input'> (POSSIBLE) to cheat the System.",
    correct: ['impossible'],
    rule: 'Приставка IM- используется для отрицания прилагательных, начинающихся с букв P или M.',
    examples: [
      'Polite -> <b>Impolite</b>',
      'Patient -> <b>Impatient</b>',
      'Perfect -> <b>Imperfect</b>',
    ],
  },
  {
    id: '66f77a88-b99c-00d1-11e2-22f33a44b55c',
    section: 'wordFormation',
    context:
      'Человек, выполняющий действие (TRAIN -> TRAINER/TRAINEE - здесь учитель).',
    text: "He was a strict <input type='text' id='answer-input'> (TEACH).",
    correct: ['teacher'],
    rule: 'Суффикс -ER образует существительное (исполнителя действия) от глагола.',
    examples: [
      'Work -> <b>Worker</b>',
      'Sing -> <b>Singer</b>',
      'Play -> <b>Player</b>',
    ],
  },
  {
    id: '77a88b99-c00d-11e2-22f3-33a44b55c66d',
    section: 'wordFormation',
    context: 'Прилагательное от POWER (мощный).',
    text: "The artifact was extremely <input type='text' id='answer-input'> (POWER).",
    correct: ['powerful'],
    rule: "Суффикс -FUL образует прилагательные со значением 'полный качества'.",
    examples: [
      'Help -> <b>Helpful</b>',
      'Use -> <b>Useful</b>',
      'Beauty -> <b>Beautiful</b>',
    ],
  },
  {
    id: '88b99c00-d11e-22f3-33a4-44b55c66d77e',
    section: 'wordFormation',
    context: 'Существительное от AGREE (соглашение).',
    text: "They made an <input type='text' id='answer-input'> (AGREE) to work together.",
    correct: ['agreement'],
    rule: 'Суффикс -MENT образует существительные от глаголов.',
    examples: [
      'Develop -> <b>Development</b>',
      'Improve -> <b>Improvement</b>',
      'Move -> <b>Movement</b>',
    ],
  },
  {
    id: '99c00d11-e22f-33a4-44b5-55c66d77e88f',
    section: 'wordFormation',
    context: 'Отрицание счастья (несчастье/страдание).',
    text: "The villain caused a lot of <input type='text' id='answer-input'> (HAPPINESS) to others.",
    correct: ['unhappiness'],
    rule: 'Приставка UN- используется для образования антонимов (Happiness -> Unhappiness).',
    examples: [
      'Happy -> <b>Unhappy</b>',
      'Known -> <b>Unknown</b>',
      'Real -> <b>Unreal</b>',
    ],
  },
  {
    id: '00d11e22-f33a-44b5-55c6-66d77e88f99a',
    section: 'wordFormation',
    context: 'Прилагательное от MAGIC (магический).',
    text: "He found a <input type='text' id='answer-input'> (MAGIC) stone.",
    correct: ['magical'],
    rule: 'Суффикс -AL образует прилагательные от существительных.',
    examples: [
      'Music -> <b>Musical</b>',
      'Nature -> <b>Natural</b>',
      'Nation -> <b>National</b>',
    ],
  },
  {
    id: '11e22f33-a44b-55c6-66d7-77e88f99a00b',
    section: 'wordFormation',
    context: 'Существительное от STRONG (сила).',
    text: "He admired the <input type='text' id='answer-input'> (STRONG) of the Sect Leader.",
    correct: ['strength'],
    rule: 'Исключение: Strong (прил.) -> Strength (сущ.). Меняется корневая гласная и добавляется -TH.',
    examples: [
      'Long -> <b>Length</b>',
      'Wide -> <b>Width</b>',
      'Deep -> <b>Depth</b>',
    ],
  },
  {
    id: '22f33a44-b55c-66d7-77e8-88f99a00b11c',
    section: 'wordFormation',
    context: 'Существительное от DIE (смерть).',
    text: "He was afraid of <input type='text' id='answer-input'> (DIE).",
    correct: ['death'],
    rule: 'Die (глагол) -> Death (существительное).',
    examples: [
      'He died yesterday.',
      '<b>Death</b> is inevitable.',
      'The death rate is high.',
    ],
  },
  {
    id: '33a44b55-c66d-77e8-88f9-99a00b11c22d',
    section: 'wordFormation',
    context: 'Прилагательное от HARM (безвредный).',
    text: "This little bunny looks <input type='text' id='answer-input'> (HARM), but it's a monster.",
    correct: ['harmless'],
    rule: 'Суффикс -LESS образует прилагательные со значением отсутствия качества.',
    examples: [
      'Use -> <b>Useless</b>',
      'End -> <b>Endless</b>',
      'Home -> <b>Homeless</b>',
    ],
  },
  {
    id: '44b55c66-d77e-88f9-99a0-00b11c22d33e',
    section: 'wordFormation',
    context: 'Глагол "переписать" (сюжет).',
    text: "He wanted to <input type='text' id='answer-input'> (WRITE) the story.",
    correct: ['rewrite'],
    rule: 'Приставка RE- означает повторное действие.',
    examples: [
      'Do -> <b>Redo</b>',
      'Play -> <b>Replay</b>',
      'Cycle -> <b>Recycle</b>',
    ],
  },
  {
    id: '55c66d77-e88f-99a0-00b1-11c22d33e44f',
    section: 'wordFormation',
    context: 'Существительное от IMPORTANT (важность).',
    text: "He didn't realize the <input type='text' id='answer-input'> (IMPORTANT) of this item.",
    correct: ['importance'],
    rule: 'Суффикс -ANCE/-ENCE образует существительные от прилагательных на -ANT/-ENT.',
    examples: [
      'Silent -> <b>Silence</b>',
      'Distant -> <b>Distance</b>',
      'Different -> <b>Difference</b>',
    ],
  },
  {
    id: '66d77e88-f99a-00b1-11c2-22d33e44f55a',
    section: 'wordFormation',
    context: 'Прилагательное от DEMON (демонический).',
    text: "He practiced <input type='text' id='answer-input'> (DEMON) arts.",
    correct: ['demonic'],
    rule: 'Суффикс -IC образует прилагательные.',
    examples: [
      'Hero -> <b>Heroic</b>',
      'Artist -> <b>Artistic</b>',
      'Base -> <b>Basic</b>',
    ],
  },
  {
    id: '77e88f99-a00b-11c2-22d3-33e44f55a66b',
    section: 'wordFormation',
    context: 'Существительное от BEGIN (начало).',
    text: "This is just the <input type='text' id='answer-input'> (BEGIN).",
    correct: ['beginning'],
    rule: 'Герундий или отглагольное существительное образуется с помощью -ING (с удвоением согласной).',
    examples: [
      'Run -> <b>Running</b>',
      'Swim -> <b>Swimming</b>',
      'Begin -> <b>Beginning</b>',
    ],
  },
  {
    id: '88f99a00-b11c-22d3-33e4-44f55a66b77c',
    section: 'wordFormation',
    context: 'Наречие от LUCK (к счастью).',
    text: "<input type='text' id='answer-input'> (LUCK), he survived the fall.",
    correct: ['luckily'],
    rule: 'Наречие образуется: Lucky -> Luckily (y меняется на i).',
    examples: [
      'Happy -> <b>Happily</b>',
      'Easy -> <b>Easily</b>',
      'Busy -> <b>Busily</b>',
    ],
  },
  {
    id: '99a00b11-c22d-33e4-44f5-55a66b77c88d',
    section: 'wordFormation',
    context: 'Существительное от INVITE (приглашение).',
    text: "He received an <input type='text' id='answer-input'> (INVITE) to the conference.",
    correct: ['invitation'],
    rule: 'Глагол на -ite образует существительное с суффиксом -ATION (Invite -> Invitation).',
    examples: [
      'Translate -> <b>Translation</b>',
      'Prepare -> <b>Preparation</b>',
      'Imagine -> <b>Imagination</b>',
    ],
  },
  {
    id: '00b11c22-d33e-44f5-55a6-66b77c88d99e',
    section: 'wordFormation',
    context: 'Прилагательное от SUN (солнечный).',
    text: "It was a bright <input type='text' id='answer-input'> (SUN) day.",
    correct: ['sunny'],
    rule: 'Суффикс -Y образует прилагательные от существительных (часто погода).',
    examples: [
      'Rain -> <b>Rainy</b>',
      'Cloud -> <b>Cloudy</b>',
      'Wind -> <b>Windy</b>',
    ],
  },
];
