import { Question } from '../../model/question';

export const articlesQuestions: Question[] = [
  {
    id: 'b1a2c3d4-e5f6-4a1b-8c9d-0e1f2a3b4c5d',
    section: 'articles',
    context:
      'Речь идет о конкретном Храме Истины, который упоминается в названии.',
    text: "The disciple walked slowly towards <input type='text' id='answer-input'> (a/an/the) Temple of Truth.",
    correct: ['the'],
    rule: "Определенный артикль 'The' используется с названиями уникальных зданий, учреждений или когда объект четко определен контекстом.",
    examples: [
      'We visited <b>the</b> British Museum.',
      'He went to <b>the</b> bank.',
      '<b>The</b> White House is in Washington.',
    ],
  },
  {
    id: 'f2e3d4c5-b6a7-4890-1c2d-3e4f5a6b7c8d',
    section: 'articles',
    context: 'Упоминание лотоса впервые как одного из множества цветков.',
    text: "He saw <input type='text' id='answer-input'> (a/an/the) beautiful lotus floating in the pond.",
    correct: ['a'],
    rule: "Неопределенный артикль 'A' используется, когда мы говорим о предмете впервые или об одном из множества подобных предметов.",
    examples: [
      'I saw <b>a</b> bird in the sky.',
      'He bought <b>a</b> new book.',
      'She is <b>a</b> teacher.',
    ],
  },
  {
    id: 'a1b2c3d4-e5f6-4789-0123-4a5b6c7d8e9f',
    section: 'articles',
    context: 'Обобщение. Лотос как вид цветка (символ).',
    text: "<input type='text' id='answer-input'> (A/The/-) Lotus is a symbol of purity in the East.",
    correct: ['The', 'A'],
    rule: "Когда мы говорим о виде растений или животных в общем смысле, можно использовать 'The' (научный/формальный стиль) или 'A' (любой представитель вида). В данном контексте 'The' звучит более поэтично.",
    examples: [
      '<b>The</b> rose is my favorite flower.',
      '<b>A</b> dog is a loyal friend.',
      '<b>The</b> tiger is dangerous.',
    ],
  },
  {
    id: '9a8b7c6d-5e4f-4321-1098-76543210fedc',
    section: 'articles',
    context: 'Абстрактное понятие "мудрость" в общем смысле.',
    text: "The Master possessed infinite <input type='text' id='answer-input'> (a/an/the/-) wisdom.",
    correct: ['-'],
    rule: 'Абстрактные неисчисляемые существительные (wisdom, love, peace) обычно используются без артикля (Zero Article).',
    examples: [
      '<b>Knowledge</b> is power.',
      'We need <b>patience</b>.',
      'He is full of <b>courage</b>.',
    ],
  },
  {
    id: '12345678-abcd-efgh-ijkl-mnopqrstuvwx',
    section: 'articles',
    context: 'Конкретная мудрость древних (уточнение "of the ancients").',
    text: "He sought <input type='text' id='answer-input'> (a/an/the) wisdom of the ancients.",
    correct: ['the'],
    rule: "Если абстрактное существительное уточняется (of the ancients), оно становится конкретным и требует артикля 'The'.",
    examples: [
      '<b>The</b> life of Napoleon was interesting.',
      '<b>The</b> education I received was good.',
      '<b>The</b> silence in the room was heavy.',
    ],
  },
  {
    id: '87654321-ijkl-mnop-qrst-uvwxyzabcdef',
    section: 'articles',
    context: 'Суперлатив: самая высокая гора.',
    text: "They climbed <input type='text' id='answer-input'> (a/an/the) highest peak to meditate.",
    correct: ['the'],
    rule: "Превосходная степень прилагательных (highest, best, most) всегда употребляется с артиклем 'The'.",
    examples: [
      'It is <b>the</b> best day ever.',
      'She is <b>the</b> smartest girl.',
      'This is <b>the</b> most expensive car.',
    ],
  },
  {
    id: 'abba1234-cccc-dddd-eeee-ffff09876543',
    section: 'articles',
    context: 'Уникальное небесное тело (солнце).',
    text: "The monks woke up before <input type='text' id='answer-input'> (a/an/the) sun rose.",
    correct: ['the'],
    rule: "Уникальные объекты (sun, moon, sky, world, universe) употребляются с артиклем 'The'.",
    examples: [
      'Look at <b>the</b> sky.',
      '<b>The</b> moon is bright tonight.',
      'He traveled around <b>the</b> world.',
    ],
  },
  {
    id: 'deadbeef-1234-5678-90ab-cdef12345678',
    section: 'articles',
    context: 'Прием пищи (завтрак).',
    text: "After meditation, they had <input type='text' id='answer-input'> (a/an/the/-) breakfast in silence.",
    correct: ['-'],
    rule: 'Названия приемов пищи (breakfast, lunch, dinner) обычно используются без артикля.',
    examples: [
      'I have <b>breakfast</b> at 8 am.',
      "Let's go out for <b>dinner</b>.",
      '<b>Lunch</b> is ready.',
    ],
  },
  {
    id: 'feedface-aaaa-bbbb-cccc-dddd12345678',
    section: 'articles',
    context: 'Группа людей, объединенная признаком (бедные).',
    text: "The Master always helped <input type='text' id='answer-input'> (a/an/the) poor.",
    correct: ['the'],
    rule: "Прилагательные в значении группы людей (the rich, the poor, the young) требуют артикля 'The'.",
    examples: [
      '<b>The rich</b> should help the poor.',
      '<b>The elderly</b> need care.',
      '<b>The blind</b> use Braille.',
    ],
  },
  {
    id: 'c0ff3344-5566-7788-9900-aabbccddeeff',
    section: 'articles',
    context: 'Время суток (утром).',
    text: "He practiced Kung Fu in <input type='text' id='answer-input'> (a/an/the) morning.",
    correct: ['the'],
    rule: "В устойчивых выражениях времени (in the morning, in the evening, in the afternoon) используется 'The'. Исключение: at night.",
    examples: [
      'I work in <b>the</b> morning.',
      'We met in <b>the</b> afternoon.',
      'Stars appear at <b>night</b>.',
    ],
  },
  {
    id: '11223344-5566-7788-99aa-bbccddeeff00',
    section: 'articles',
    context: 'Игра на музыкальном инструменте (флейта).',
    text: "The old man played <input type='text' id='answer-input'> (a/an/the/-) flute beautifully.",
    correct: ['the'],
    rule: "С музыкальными инструментами после глагола 'play' используется определенный артикль 'The'.",
    examples: [
      'Can you play <b>the</b> guitar?',
      'She plays <b>the</b> piano.',
      'He learns <b>the</b> violin.',
    ],
  },
  {
    id: '99887766-5544-3322-1100-aabbccddeeff',
    section: 'articles',
    context: 'Единственный в своем роде титул/роль (Настоятель).',
    text: "He was appointed <input type='text' id='answer-input'> (a/an/the/-) Abbot of the monastery.",
    correct: ['-', 'the'],
    rule: "Если говорится о должности/титуле, который занимает только один человек, артикль часто опускается, но 'the' тоже возможно.",
    examples: [
      'He became <b>President</b>.',
      'She was elected <b>captain</b> of the team.',
      'He is <b>the</b> CEO of the company.',
    ],
  },
  {
    id: 'aa11bb22-cc33-dd44-ee55-ff6677889900',
    section: 'articles',
    context: 'Горная цепь (Гималаи).',
    text: "The temple was located somewhere in <input type='text' id='answer-input'> (a/an/the/-) Himalayas.",
    correct: ['the'],
    rule: "Названия горных цепей (Himalayas, Alps, Andes) используются с 'The'. Одиночные горы (Everest) - без артикля.",
    examples: [
      'We flew over <b>the</b> Alps.',
      '<b>The</b> Urals divide Europe and Asia.',
      'He climbed <b>Mount</b> Everest.',
    ],
  },
  {
    id: '77777777-aaaa-bbbb-cccc-dddd12345678',
    section: 'articles',
    context: 'Один и тот же путь (same).',
    text: "We are walking <input type='text' id='answer-input'> (a/an/the) same path.",
    correct: ['the'],
    rule: "Слово 'same' практически всегда требует артикля 'The'.",
    examples: [
      'We have <b>the same</b> problem.',
      'It is <b>the same</b> book.',
      'At <b>the same</b> time.',
    ],
  },
  {
    id: '88888888-eeee-ffff-aaaa-bbbbccccdddd',
    section: 'articles',
    context: 'Профессия/статус (монах).',
    text: "His father was <input type='text' id='answer-input'> (a/an/the) monk.",
    correct: ['a'],
    rule: "Перед названием профессии или статуса, когда говорим о ком-то одном, используется неопределенный артикль 'A/An'.",
    examples: [
      'I am <b>a</b> student.',
      'He is <b>an</b> engineer.',
      'She wants to be <b>a</b> doctor.',
    ],
  },
  {
    id: '55555555-4444-3333-2222-111111111111',
    section: 'articles',
    context: 'Восклицание (Какой прекрасный день!).',
    text: "What <input type='text' id='answer-input'> (a/an/the/-) peaceful place!",
    correct: ['a'],
    rule: "В восклицательных предложениях после 'What' перед исчисляемым существительным в единственном числе ставится 'A'.",
    examples: [
      'What <b>a</b> nice day!',
      'What <b>a</b> surprise!',
      'What <b>a</b> pity!',
    ],
  },
  {
    id: '22222222-3333-4444-5555-666666666666',
    section: 'articles',
    context: 'Стороны света (Восток).',
    text: "The wind blew from <input type='text' id='answer-input'> (a/an/the) North.",
    correct: ['the'],
    rule: "Названия сторон света (North, South, East, West) употребляются с 'The', когда обозначают направление или регион.",
    examples: [
      'The sun sets in <b>the</b> West.',
      'He lives in <b>the</b> North.',
      'Go to <b>the</b> South.',
    ],
  },
  {
    id: '99999999-8888-7777-6666-555555555555',
    section: 'articles',
    context: 'Порядковое числительное (первый шаг).',
    text: "Taking <input type='text' id='answer-input'> (a/an/the) first step is the hardest.",
    correct: ['the'],
    rule: "Порядковые числительные (first, second, third, next, last) требуют определенного артикля 'The'.",
    examples: [
      'This is <b>the</b> first time.',
      'Take <b>the</b> second turn.',
      'Who was <b>the</b> last person?',
    ],
  },
  {
    id: 'abababab-cdcd-efef-ghgh-ijijijijijij',
    section: 'articles',
    context: 'Озеро (название).',
    text: "The monastery stood near <input type='text' id='answer-input'> (a/an/the/-) Lake Baikal.",
    correct: ['-'],
    rule: "Если в названии озера есть слово 'Lake', артикль не ставится (Lake Baikal). Если просто название (The Baikal) — нужен артикль.",
    examples: [
      'We visited <b>Lake</b> Ontario.',
      '<b>The</b> Baikal is deep.',
      'I love <b>Lake</b> Michigan.',
    ],
  },
  {
    id: 'fefefefe-dcd-cbcb-aaaa-121212121212',
    section: 'articles',
    context: 'Существительное + номер (Глава 5).',
    text: "Read <input type='text' id='answer-input'> (a/an/the/-) Chapter 5 to understand the ritual.",
    correct: ['-'],
    rule: 'Артикль не ставится перед существительным, за которым следует номер (Chapter 5, Room 10, Page 30).',
    examples: [
      'Open <b>page</b> 10.',
      'He stays in <b>Room</b> 202.',
      'Look at <b>figure</b> 3.',
    ],
  },
];
