import { Question } from '../../model/question';

export const prepositionsQuestions: Question[] = [
  {
    id: '4a6b1c3d-9e2f-45a7-b8c0-d1e2f3a4b5c6',
    section: 'prepositions',
    context: 'Сосредоточиться на чем-то (медитация).',
    text: "The disciple tried to concentrate <input type='text' id='answer-input'> (in/on/at) his breathing.",
    correct: ['on'],
    rule: 'Глагол Concentrate всегда используется с предлогом ON.',
    examples: [
      'Focus <b>on</b> your work.',
      'I cannot concentrate <b>on</b> reading.',
      'It depends <b>on</b> you.',
    ],
  },
  {
    id: '7b8c9d0e-1f2a-3b4c-5d6e-7f8a9b0c1d2e',
    section: 'prepositions',
    context: 'Бояться чего-то (внутренних демонов).',
    text: "There is no need to be afraid <input type='text' id='answer-input'> (from/of/by) the shadows.",
    correct: ['of'],
    rule: 'Прилагательное Afraid (бояться) требует предлога OF.',
    examples: [
      'Are you afraid <b>of</b> spiders?',
      'He is afraid <b>of</b> the dark.',
      "Don't be afraid <b>of</b> making mistakes.",
    ],
  },
  {
    id: '3f4e5d6c-7b8a-9012-3456-7890abcdef12',
    section: 'prepositions',
    context: 'Слушать кого-то (Учителя).',
    text: "You must listen <input type='text' id='answer-input'> (at/to/for) the Master carefully.",
    correct: ['to'],
    rule: 'Глагол Listen всегда требует предлога TO перед объектом.',
    examples: [
      'Listen <b>to</b> me.',
      'She listens <b>to</b> music.',
      "He didn't listen <b>to</b> advice.",
    ],
  },
  {
    id: '1a2b3c4d-5e6f-7890-1234-567890abcdef',
    section: 'prepositions',
    context: 'Прибыть в небольшое место (храм, станция).',
    text: "When they arrived <input type='text' id='answer-input'> (in/at/to) the temple, it was raining.",
    correct: ['at'],
    rule: 'Arrive AT используется для зданий, станций, конкретных точек. Arrive IN — для городов и стран.',
    examples: [
      'We arrived <b>at</b> the hotel.',
      'They arrived <b>in</b> London.',
      'When do you arrive <b>at</b> the airport?',
    ],
  },
  {
    id: '2b3c4d5e-6f7a-8901-2345-678901abcdef',
    section: 'prepositions',
    context: 'Быть полным чего-то (спокойствия, энергии).',
    text: "The valley was full <input type='text' id='answer-input'> (with/of/by) blooming lotuses.",
    correct: ['of'],
    rule: 'Прилагательное Full используется с предлогом OF.',
    examples: [
      'The cup is full <b>of</b> water.',
      'Life is full <b>of</b> surprises.',
      'The room was full <b>of</b> people.',
    ],
  },
  {
    id: 'cdef1234-5678-90ab-cdef-1234567890ab',
    section: 'prepositions',
    context: 'Ждать кого-то.',
    text: "He has been waiting <input type='text' id='answer-input'> (to/for/on) enlightenment for years.",
    correct: ['for'],
    rule: 'Wait всегда используется с предлогом FOR (ждать кого-то/чего-то).',
    examples: [
      'Wait <b>for</b> me.',
      'I am waiting <b>for</b> the bus.',
      'They waited <b>for</b> a reply.',
    ],
  },
  {
    id: 'ef123456-7890-abcd-ef12-34567890abcd',
    section: 'prepositions',
    context: 'Хорош в чем-то (навык, Кунг-фу).',
    text: "The young monk is very good <input type='text' id='answer-input'> (in/at/on) martial arts.",
    correct: ['at'],
    rule: "Выражение 'быть хорошим/плохим в чем-то' — Good AT / Bad AT.",
    examples: [
      'She is good <b>at</b> math.',
      'He is bad <b>at</b> drawing.',
      'Are you good <b>at</b> tennis?',
    ],
  },
  {
    id: '567890ab-cdef-1234-5678-90abcdef1234',
    section: 'prepositions',
    context: 'Гордиться чем-то/кем-то.',
    text: "The Master was proud <input type='text' id='answer-input'> (for/of/with) his student's progress.",
    correct: ['of'],
    rule: 'Proud (гордый) используется с предлогом OF.',
    examples: [
      'I am proud <b>of</b> you.',
      'They are proud <b>of</b> their country.',
      'He was proud <b>of</b> his son.',
    ],
  },
  {
    id: '90abcdef-1234-5678-90ab-cdef12345678',
    section: 'prepositions',
    context: 'Зависеть от чего-то (от воли небес).',
    text: "Your success depends <input type='text' id='answer-input'> (from/of/on) your effort.",
    correct: ['on'],
    rule: 'Depend (зависеть) всегда используется с предлогом ON.',
    examples: [
      'It depends <b>on</b> the weather.',
      'Children depend <b>on</b> parents.',
      'Do not depend <b>on</b> luck.',
    ],
  },
  {
    id: 'def12345-6789-0abc-def1-234567890abc',
    section: 'prepositions',
    context: 'Верить во что-то (в истину, в себя).',
    text: "You must believe <input type='text' id='answer-input'> (to/in/at) yourself to find the path.",
    correct: ['in'],
    rule: 'Believe (верить во что-то/кого-то) используется с предлогом IN.',
    examples: [
      'Do you believe <b>in</b> ghosts?',
      'I believe <b>in</b> God.',
      'Believe <b>in</b> your dreams.',
    ],
  },
  {
    id: '34567890-abcd-ef12-3456-7890abcdef12',
    section: 'prepositions',
    context: 'Злиться на кого-то.',
    text: "Do not be angry <input type='text' id='answer-input'> (on/to/with) your brother.",
    correct: ['with', 'at'],
    rule: 'Angry WITH someone (на кого-то). Angry AT/ABOUT something (на что-то).',
    examples: [
      'She is angry <b>with</b> me.',
      'He was angry <b>about</b> the delay.',
      'Why are you angry <b>with</b> him?',
    ],
  },
  {
    id: '7890abcd-ef12-3456-7890-abcdef123456',
    section: 'prepositions',
    context: 'Отличаться от.',
    text: "This lotus is different <input type='text' id='answer-input'> (from/than/of) the others.",
    correct: ['from'],
    rule: 'Different (отличный, другой) используется с предлогом FROM. (В разговорном US также than, но from — классика).',
    examples: [
      'My car is different <b>from</b> yours.',
      'Tea is different <b>from</b> coffee.',
      'People are different <b>from</b> each other.',
    ],
  },
  {
    id: 'bcdef123-4567-890a-bcde-f1234567890a',
    section: 'prepositions',
    context: 'Интересоваться чем-то (древними свитками).',
    text: "She is interested <input type='text' id='answer-input'> (at/in/on) ancient history.",
    correct: ['in'],
    rule: 'Interested всегда используется с предлогом IN.',
    examples: [
      'Are you interested <b>in</b> art?',
      'He is interested <b>in</b> buying a car.',
      'I am not interested <b>in</b> sports.',
    ],
  },
  {
    id: 'f1234567-890a-bcde-f123-4567890abcde',
    section: 'prepositions',
    context: 'Принадлежать кому-то.',
    text: "Does this sword belong <input type='text' id='answer-input'> (for/to/with) you?",
    correct: ['to'],
    rule: 'Belong (принадлежать) требует предлога TO.',
    examples: [
      'This bag belongs <b>to</b> me.',
      'Does it belong <b>to</b> anyone?',
      'The future belongs <b>to</b> us.',
    ],
  },
  {
    id: 'a1b2c3d4-0000-1111-2222-333333333333',
    section: 'prepositions',
    context: 'Быть известным чем-то.',
    text: "The temple is famous <input type='text' id='answer-input'> (for/by/with) its golden statue.",
    correct: ['for'],
    rule: 'Famous (известный) используется с предлогом FOR (чем известен).',
    examples: [
      'France is famous <b>for</b> wine.',
      'He is famous <b>for</b> his songs.',
      'This place is famous <b>for</b> seafood.',
    ],
  },
  {
    id: 'b2c3d4e5-1111-2222-3333-444444444444',
    section: 'prepositions',
    context: 'Извиняться за что-то.',
    text: "He apologized <input type='text' id='answer-input'> (for/about/of) being late to the prayer.",
    correct: ['for'],
    rule: 'Apologize FOR something (за что-то) TO someone (перед кем-то).',
    examples: [
      'I apologize <b>for</b> the mistake.',
      'She apologized <b>to</b> him.',
      'He apologized <b>for</b> interrupting.',
    ],
  },
  {
    id: 'c3d4e5f6-2222-3333-4444-555555555555',
    section: 'prepositions',
    context: 'Смеяться над кем-то (неуважительно).',
    text: "It is forbidden to laugh <input type='text' id='answer-input'> (on/at/to) others' mistakes.",
    correct: ['at'],
    rule: 'Laugh AT someone (смеяться над кем-то).',
    examples: [
      "Don't laugh <b>at</b> him.",
      'They laughed <b>at</b> the joke.',
      'Why are you laughing <b>at</b> me?',
    ],
  },
  {
    id: 'd4e5f6a7-3333-4444-5555-666666666666',
    section: 'prepositions',
    context: 'Смотреть на что-то.',
    text: "Look <input type='text' id='answer-input'> (on/at/to) the lotus flower closely.",
    correct: ['at'],
    rule: 'Look AT something (смотреть на что-то).',
    examples: [
      'Look <b>at</b> the board.',
      'She looked <b>at</b> her watch.',
      'Look <b>at</b> me!',
    ],
  },
  {
    id: 'e5f6a7b8-4444-5555-6666-777777777777',
    section: 'prepositions',
    context: 'Страдать от чего-то (болезни, иллюзий).',
    text: "He suffers <input type='text' id='answer-input'> (from/of/by) a lack of patience.",
    correct: ['from'],
    rule: 'Suffer FROM (страдать от болезни/недуга).',
    examples: [
      'She suffers <b>from</b> headaches.',
      'He suffers <b>from</b> insomnia.',
      'Many suffer <b>from</b> hunger.',
    ],
  },
  {
    id: 'f6a7b8c9-5555-6666-7777-888888888888',
    section: 'prepositions',
    context: 'Напоминать о чем-то.',
    text: "This melody reminds me <input type='text' id='answer-input'> (about/of/for) my home.",
    correct: ['of'],
    rule: 'Remind someone OF something (напоминать кому-то о чем-то - вызывать воспоминания).',
    examples: [
      'You remind me <b>of</b> your father.',
      'It reminds me <b>of</b> our trip.',
      'This smell reminds me <b>of</b> Christmas.',
    ],
  },
];
