import { Question } from '../../model/question';

export const verbsQuestions: Question[] = [
  {
    id: '11112222-3333-4444-5555-666677778888',
    section: 'verbs',
    context: 'Длительное действие в прошлом, прерванное другим.',
    text: "The Master <input type='text' id='answer-input'> (meditate) when the earthquake started.",
    correct: ['was meditating'],
    rule: 'Past Continuous (was/were + ing) используется для длительного действия, которое происходило в момент, когда случилось другое краткое действие.',
    examples: [
      'I <b>was sleeping</b> when you called.',
      'It <b>was raining</b> when we left.',
      'She <b>was cooking</b> when he arrived.',
    ],
  },
  {
    id: '22223333-4444-5555-6666-777788889999',
    section: 'verbs',
    context:
      'Действие, которое завершилось к моменту в прошлом (предпрошедшее).',
    text: "By the time the sun rose, the disciple <input type='text' id='answer-input'> (finish) his prayers.",
    correct: ['had finished'],
    rule: 'Past Perfect (had + V3) используется для действия, которое завершилось до определенного момента или другого действия в прошлом.',
    examples: [
      'I <b>had eaten</b> before he came.',
      "She <b>had left</b> by 5 o'clock.",
      'We <b>had seen</b> the film before.',
    ],
  },
  {
    id: '33334444-5555-6666-7777-88889999aaaa',
    section: 'verbs',
    context: 'Результат в настоящем (он выучил урок, знает его сейчас).',
    text: "I <input type='text' id='answer-input'> (learn) the secret of the Lotus. Now I understand.",
    correct: ['have learned', 'have learnt'],
    rule: 'Present Perfect (have/has + V3) используется, когда действие произошло в прошлом, но его результат важен сейчас.',
    examples: [
      "I <b>have lost</b> my keys (I can't enter).",
      'She <b>has broken</b> her leg.',
      'We <b>have finished</b> the work.',
    ],
  },
  {
    id: '44445555-6666-7777-8888-9999aaaabbbb',
    section: 'verbs',
    context: 'Пассивный залог (храм был построен кем-то).',
    text: "The Temple of Truth <input type='text' id='answer-input'> (build) three centuries ago.",
    correct: ['was built'],
    rule: 'Past Simple Passive (was/were + V3) используется, когда действие совершено над объектом в прошлом.',
    examples: [
      'The book <b>was written</b> by him.',
      'The car <b>was stolen</b> yesterday.',
      'Detailed records <b>were kept</b>.',
    ],
  },
  {
    id: '55556666-7777-8888-9999-aaaabbbbcccc',
    section: 'verbs',
    context: 'Условное предложение 1 типа (реальное будущее).',
    text: "If you practice daily, you <input type='text' id='answer-input'> (become) strong.",
    correct: ['will become'],
    rule: 'First Conditional: If + Present Simple, ... Future Simple (will + V). Реальное условие в будущем.',
    examples: [
      'If it rains, we <b>will stay</b> home.',
      'If you study, you <b>will pass</b>.',
      'If he comes, I <b>will tell</b> him.',
    ],
  },
  {
    id: '66667777-8888-9999-aaaa-bbbbccccdddd',
    section: 'verbs',
    context: 'Условное предложение 2 типа (нереальное настоящее/мечта).',
    text: "If I <input type='text' id='answer-input'> (be) you, I would choose the path of peace.",
    correct: ['were', 'was'],
    rule: "Second Conditional: If + Past Simple, ... would + V. Совет или воображаемая ситуация. 'If I were' - формальный/классический вариант.",
    examples: [
      'If I <b>were</b> rich, I would travel.',
      'If he <b>knew</b>, he would help.',
      'If I <b>were</b> a bird, I would fly.',
    ],
  },
  {
    id: '77778888-9999-aaaa-bbbb-ccccddddeeee',
    section: 'verbs',
    context: 'Привычка в прошлом, которой больше нет.',
    text: "The old master <input type='text' id='answer-input'> (use to) travel a lot when he was young.",
    correct: ['used to'],
    rule: "Конструкция 'used to + verb' описывает регулярные действия или состояния в прошлом, которых больше нет.",
    examples: [
      'I <b>used to</b> smoke, but I quit.',
      'He <b>used to</b> live in Paris.',
      'We <b>used to</b> play together.',
    ],
  },
  {
    id: '88889999-aaaa-bbbb-cccc-ddddeeeeffff',
    section: 'verbs',
    context: 'Будущее длительное (в определенный момент в будущем).',
    text: "Tomorrow at this time, we <input type='text' id='answer-input'> (meditate) under the waterfall.",
    correct: ['will be meditating'],
    rule: 'Future Continuous (will be + ing) — действие будет в процессе в определенный момент в будущем.',
    examples: [
      'At 5 pm, I <b>will be flying</b> to NY.',
      "Don't call, I <b>will be sleeping</b>.",
      'He <b>will be working</b> all day.',
    ],
  },
  {
    id: '9999aaaa-bbbb-cccc-dddd-eeeeffff0000',
    section: 'verbs',
    context: 'Герундий после определенных глаголов (stop).',
    text: "The Master told him to stop <input type='text' id='answer-input'> (worry) about the future.",
    correct: ['worrying'],
    rule: "После глагола 'stop' (прекратить действие) используется герундий (V+ing). Stop to do — остановиться, чтобы сделать что-то другое.",
    examples: [
      'Stop <b>talking</b>.',
      'He stopped <b>smoking</b>.',
      'I enjoy <b>reading</b>.',
    ],
  },
  {
    id: 'aaaabbbb-cccc-dddd-eeee-ffff00001111',
    section: 'verbs',
    context: 'Инфинитив после глагола want.',
    text: "The disciple wants <input type='text' id='answer-input'> (learn) the ultimate technique.",
    correct: ['to learn'],
    rule: "После глагола 'want' используется инфинитив с частицей 'to'.",
    examples: [
      'I want <b>to go</b> home.',
      'She wants <b>to buy</b> it.',
      'They want <b>to help</b>.',
    ],
  },
  {
    id: 'bbbbcccc-dddd-eeee-ffff-000011112222',
    section: 'verbs',
    context:
      'Действие, которое началось в прошлом и длится до сих пор (Present Perfect Continuous).',
    text: "He <input type='text' id='answer-input'> (wait) for the teacher for three hours.",
    correct: ['has been waiting'],
    rule: 'Present Perfect Continuous (have/has been + ing) — действие началось в прошлом и продолжается до сих пор (акцент на длительность).',
    examples: [
      'I <b>have been working</b> here for 5 years.',
      'It <b>has been raining</b> since morning.',
      'How long <b>have you been waiting</b>?',
    ],
  },
  {
    id: 'ccccdddd-eeee-ffff-0000-111122223333',
    section: 'verbs',
    context: 'Косвенная речь (согласование времен).',
    text: "He said that he <input type='text' id='answer-input'> (be) ready to fight.",
    correct: ['was'],
    rule: 'В косвенной речи, если главное предложение в прошлом (He said), придаточное тоже сдвигается в прошлое (is -> was).',
    examples: [
      'He said he <b>liked</b> it (like -> liked).',
      'She said she <b>was</b> busy.',
      'They told me they <b>were</b> leaving.',
    ],
  },
  {
    id: 'ddddeeee-ffff-0000-1111-222233334444',
    section: 'verbs',
    context: 'Модальный глагол (запрет).',
    text: "You <input type='text' id='answer-input'> (must not / don't have to) enter the sacred room.",
    correct: ['must not', "mustn't"],
    rule: "Must not (mustn't) выражает строгий запрет. Don't have to — отсутствие необходимости.",
    examples: [
      'You <b>must not</b> smoke here.',
      'Visitors <b>must not</b> touch the art.',
      "You <b>mustn't</b> be late.",
    ],
  },
  {
    id: 'eeeeffff-0000-1111-2222-333344445555',
    section: 'verbs',
    context: 'Глаголы состояния (State verbs) не употребляются в Continuous.',
    text: "Currently, I <input type='text' id='answer-input'> (understand) the lesson completely.",
    correct: ['understand'],
    rule: 'Глаголы умственной деятельности (understand, know, believe) не используются во временах группы Continuous, даже если действие происходит сейчас.',
    examples: [
      'I <b>know</b> the answer (not am knowing).',
      'Do you <b>believe</b> me?',
      'She <b>likes</b> ice cream.',
    ],
  },
  {
    id: 'ffff0000-1111-2222-3333-444455556666',
    section: 'verbs',
    context: 'Планы на будущее (going to).',
    text: "Look at those clouds! It <input type='text' id='answer-input'> (go to) rain.",
    correct: ['is going to', "'s going to"],
    rule: 'To be going to используется для предсказаний, основанных на очевидных признаках (облака -> дождь), или для планов.',
    examples: [
      'It <b>is going to</b> snow.',
      'She <b>is going to</b> buy a car.',
      'Watch out! You <b>are going to</b> fall.',
    ],
  },
  {
    id: '00001111-2222-3333-4444-555566667777',
    section: 'verbs',
    context: 'Каузативная форма (сделать что-то чужими руками).',
    text: "The Abbot <input type='text' id='answer-input'> (have) the roof repaired yesterday.",
    correct: ['had'],
    rule: 'Have something done (had + object + V3) означает, что кто-то выполнил работу для подлежащего (нанял кого-то).',
    examples: [
      'I <b>had</b> my hair cut.',
      'She <b>has</b> her car washed.',
      'We <b>will have</b> the house painted.',
    ],
  },
  {
    id: '11112222-3333-4444-5555-666677778899',
    section: 'verbs',
    context: 'Конструкция I wish (сожаление о настоящем).',
    text: "I wish I <input type='text' id='answer-input'> (know) the truth now.",
    correct: ['knew'],
    rule: 'В конструкции I wish для сожаления о настоящем используется Past Simple (know -> knew).',
    examples: [
      'I wish I <b>had</b> more money.',
      'I wish I <b>lived</b> in Spain.',
      'She wishes she <b>was</b> taller.',
    ],
  },
  {
    id: '22223333-4444-5555-6666-777788889900',
    section: 'verbs',
    context: 'Future Perfect (завершить к моменту в будущем).',
    text: "By next year, I <input type='text' id='answer-input'> (finish) my training.",
    correct: ['will have finished'],
    rule: 'Future Perfect (will have + V3) описывает действие, которое будет завершено к определенному моменту в будущем.',
    examples: [
      'I <b>will have done</b> it by tomorrow.',
      'She <b>will have arrived</b> by 6.',
      'We <b>will have built</b> the house by June.',
    ],
  },
  {
    id: '33334444-5555-6666-7777-8888999900aa',
    section: 'verbs',
    context: 'Послелоги/фразовые глаголы (Give up).',
    text: "Never <input type='text' id='answer-input'> (give) up on your dreams.",
    correct: ['give'],
    rule: 'Give up (сдаваться, бросать). В императиве (повелительном наклонении) используется базовая форма.',
    examples: [
      "Don't <b>give</b> up.",
      'He <b>gave</b> up smoking.',
      'Never <b>give</b> in.',
    ],
  },
  {
    id: '44445555-6666-7777-8888-999900aabbcc',
    section: 'verbs',
    context: 'Make vs Do (Make a mistake).',
    text: "Try not to <input type='text' id='answer-input'> (make/do) mistakes during the ritual.",
    correct: ['make'],
    rule: 'Слово mistake употребляется с глаголом MAKE, а не do.',
    examples: [
      '<b>Make</b> a mistake.',
      '<b>Make</b> a decision.',
      '<b>Do</b> your homework.',
    ],
  },
];
