import { Question } from '../../model/question';

export const wordFormationQuestions: Question[] = [
  {
    id: '5e7f1a2b-3c4d-5e6f-7a8b-9c0d1e2f3a4b',
    section: 'wordFormation',
    context: 'Существительное от прилагательного DARK (Тьма).',
    text: "The disciple was afraid of the <input type='text' id='answer-input'> (DARK) within his soul.",
    correct: ['darkness'],
    rule: 'Суффикс -NESS образует абстрактные существительные от прилагательных.',
    examples: [
      'Happy -> <b>Happiness</b>',
      'Kind -> <b>Kindness</b>',
      'Sad -> <b>Sadness</b>',
    ],
  },
  {
    id: '6f8a2b3c-4d5e-6f7a-8b9c-0d1e2f3a4b5c',
    section: 'wordFormation',
    context: 'Существительное от прилагательного SILENT (Тишина).',
    text: "The temple was wrapped in total <input type='text' id='answer-input'> (SILENT).",
    correct: ['silence'],
    rule: 'Прилагательные на -ENT часто образуют существительные с суффиксом -ENCE.',
    examples: [
      'Intelligent -> <b>Intelligence</b>',
      'Patient -> <b>Patience</b>',
      'Absent -> <b>Absence</b>',
    ],
  },
  {
    id: '7a9b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
    section: 'wordFormation',
    context: 'Существительное от глагола KNOW (Знание).',
    text: "The Master shared his secret <input type='text' id='answer-input'> (KNOW) with the boy.",
    correct: ['knowledge'],
    rule: 'Knowledge — существительное, образованное от глагола Know.',
    examples: [
      'He has broad <b>knowledge</b>.',
      'To the best of my <b>knowledge</b>.',
      'Knowledge is power.',
    ],
  },
  {
    id: '8b0c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e',
    section: 'wordFormation',
    context: 'Существительное от прилагательного TRUE (Истина).',
    text: "He traveled far to find the <input type='text' id='answer-input'> (TRUE).",
    correct: ['truth'],
    rule: 'Существительное от True — Truth (изменение корневой гласной + th).',
    examples: [
      'Tell the <b>truth</b>.',
      'Warm -> <b>Warmth</b>',
      'Strong -> <b>Strength</b>',
    ],
  },
  {
    id: '9c1d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f',
    section: 'wordFormation',
    context: 'Существительное от прилагательного WISE (Мудрость).',
    text: "His eyes were full of ancient <input type='text' id='answer-input'> (WISE).",
    correct: ['wisdom'],
    rule: 'Wise преобразуется в Wisdom (изменение формы + dom).',
    examples: [
      'Free -> <b>Freedom</b>',
      'King -> <b>Kingdom</b>',
      'Bored -> <b>Boredom</b>',
    ],
  },
  {
    id: '0d2e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a',
    section: 'wordFormation',
    context: 'Существительное от прилагательного STRONG (Сила).',
    text: "Meditation gives you inner <input type='text' id='answer-input'> (STRONG).",
    correct: ['strength'],
    rule: 'Strong -> Strength (изменение гласной + th).',
    examples: [
      'Long -> <b>Length</b>',
      'Wide -> <b>Width</b>',
      'Deep -> <b>Depth</b>',
    ],
  },
  {
    id: '1e3f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b',
    section: 'wordFormation',
    context: 'Прилагательное от существительного BEAUTY (Красивый).',
    text: "The lotus was the most <input type='text' id='answer-input'> (BEAUTY) flower in the pond.",
    correct: ['beautiful'],
    rule: "Суффикс -FUL образует прилагательные со значением 'полный качества'. Y меняется на I.",
    examples: [
      'Use -> <b>Useful</b>',
      'Color -> <b>Colorful</b>',
      'Power -> <b>Powerful</b>',
    ],
  },
  {
    id: '2f4a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c',
    section: 'wordFormation',
    context: 'Прилагательное от существительного PEACE (Мирный).',
    text: "It was a <input type='text' id='answer-input'> (PEACE) morning in the mountains.",
    correct: ['peaceful'],
    rule: 'Peace -> Peaceful (мирный, спокойный).',
    examples: [
      'Help -> <b>Helpful</b>',
      'Care -> <b>Careful</b>',
      'Success -> <b>Successful</b>',
    ],
  },
  {
    id: '3a5b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
    section: 'wordFormation',
    context:
      'Прилагательное с отрицательным префиксом от POSSIBLE (Невозможно).',
    text: "It seemed <input type='text' id='answer-input'> (POSSIBLE) to climb that wall.",
    correct: ['impossible'],
    rule: 'Префикс IM- используется для отрицания перед словами, начинающимися с P или M.',
    examples: [
      'Polite -> <b>Impolite</b>',
      'Patient -> <b>Impatient</b>',
      'Moral -> <b>Immoral</b>',
    ],
  },
  {
    id: '4b6c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e',
    section: 'wordFormation',
    context:
      'Существительное от глагола CULTIVATE (Тот, кто совершенствуется).',
    text: "The young <input type='text' id='answer-input'> (CULTIVATE) trained hard every day.",
    correct: ['cultivator'],
    rule: 'Суффикс -OR (или -ER) обозначает деятеля (человека, выполняющего действие).',
    examples: [
      'Act -> <b>Actor</b>',
      'Invent -> <b>Inventor</b>',
      'Teach -> <b>Teacher</b>',
    ],
  },
  {
    id: '5c7d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f',
    section: 'wordFormation',
    context: 'Наречие от прилагательного SILENT (Молча/Тихо).',
    text: "The monks ate <input type='text' id='answer-input'> (SILENT).",
    correct: ['silently'],
    rule: 'Наречия образа действия обычно образуются добавлением суффикса -LY к прилагательному.',
    examples: [
      'Quick -> <b>Quickly</b>',
      'Happy -> <b>Happily</b>',
      'Loud -> <b>Loudly</b>',
    ],
  },
  {
    id: '6d8e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a',
    section: 'wordFormation',
    context: 'Существительное от прилагательного PURE (Чистота).',
    text: "The white lotus symbolizes <input type='text' id='answer-input'> (PURE).",
    correct: ['purity'],
    rule: 'Pure -> Purity. Суффикс -ITY образует абстрактные существительные.',
    examples: [
      'Active -> <b>Activity</b>',
      'Real -> <b>Reality</b>',
      'Able -> <b>Ability</b>',
    ],
  },
  {
    id: '7e9f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b',
    section: 'wordFormation',
    context: 'Прилагательное от существительного DANGER (Опасный).',
    text: "The path to the temple is <input type='text' id='answer-input'> (DANGER).",
    correct: ['dangerous'],
    rule: 'Суффикс -OUS образует прилагательные.',
    examples: [
      'Fame -> <b>Famous</b>',
      'Nerve -> <b>Nervous</b>',
      'Poison -> <b>Poisonous</b>',
    ],
  },
  {
    id: '8f0a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c',
    section: 'wordFormation',
    context: 'Существительное от прилагательного DEEP (Глубина).',
    text: "The <input type='text' id='answer-input'> (DEEP) of the lake is unknown.",
    correct: ['depth'],
    rule: 'Deep -> Depth (изменение гласной + th).',
    examples: [
      'Long -> <b>Length</b>',
      'Strong -> <b>Strength</b>',
      'Broad -> <b>Breadth</b>',
    ],
  },
  {
    id: '9a1b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d',
    section: 'wordFormation',
    context: 'Существительное от глагола MEDITATE (Медитация).',
    text: "Morning <input type='text' id='answer-input'> (MEDITATE) helps to clear the mind.",
    correct: ['meditation'],
    rule: 'Глаголы на -ATE образуют существительные с суффиксом -ION.',
    examples: [
      'Educate -> <b>Education</b>',
      'Create -> <b>Creation</b>',
      'Translate -> <b>Translation</b>',
    ],
  },
  {
    id: '0b2c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e',
    section: 'wordFormation',
    context: 'Прилагательное от существительного MYSTERY (Таинственный).',
    text: "A <input type='text' id='answer-input'> (MYSTERY) stranger appeared at the gate.",
    correct: ['mysterious'],
    rule: 'Mystery -> Mysterious (y меняется на i + ous).',
    examples: [
      'Victory -> <b>Victorious</b>',
      'Fury -> <b>Furious</b>',
      'Glory -> <b>Glorious</b>',
    ],
  },
  {
    id: '1c3d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f',
    section: 'wordFormation',
    context: 'Существительное от глагола DECIDE (Решение).',
    text: "It was a difficult <input type='text' id='answer-input'> (DECIDE) to leave the monastery.",
    correct: ['decision'],
    rule: 'Decide -> Decision (de -> s + ion).',
    examples: [
      'Conclude -> <b>Conclusion</b>',
      'Divide -> <b>Division</b>',
      'Explode -> <b>Explosion</b>',
    ],
  },
  {
    id: '2d4e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a',
    section: 'wordFormation',
    context: 'Отрицательное прилагательное от HONEST (Нечестный).',
    text: "A warrior must not be <input type='text' id='answer-input'> (HONEST).",
    correct: ['dishonest'],
    rule: 'Префикс DIS- используется для отрицания.',
    examples: [
      'Like -> <b>Dislike</b>',
      'Agree -> <b>Disagree</b>',
      'Appear -> <b>Disappear</b>',
    ],
  },
  {
    id: '3e5f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b',
    section: 'wordFormation',
    context: 'Существительное от глагола ENLIGHTEN (Просветление).',
    text: "He finally reached <input type='text' id='answer-input'> (ENLIGHTEN).",
    correct: ['enlightenment'],
    rule: 'Суффикс -MENT образует существительные от глаголов.',
    examples: [
      'Develop -> <b>Development</b>',
      'Move -> <b>Movement</b>',
      'Agree -> <b>Agreement</b>',
    ],
  },
  {
    id: '4f6a0b1c-2d3e-4f5a-6b7c-8d9e0f1a2b3c',
    section: 'wordFormation',
    context: 'Прилагательное от глагола FORGET (Незабываемый).',
    text: "The journey was <input type='text' id='answer-input'> (FORGET) - un...",
    correct: ['unforgettable'],
    rule: 'Forget -> Unforgettable. Префикс UN- (отрицание) и суффикс -ABLE (возможность). Удваивается T.',
    examples: [
      'Believable -> <b>Unbelievable</b>',
      'Comfortable -> <b>Uncomfortable</b>',
      'Predictable -> <b>Unpredictable</b>',
    ],
  },
];
